# Generated by Django 4.2.2 on 2023-09-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "username",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="AdminInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("email", models.CharField(max_length=64)),
                (
                    "accessLevel",
                    models.CharField(
                        choices=[("SuperUser", "SuperUser")], max_length=32
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AdminInfo",
                        to="eadmin.admin",
                    ),
                ),
            ],
        ),
    ]
