# Generated by Django 4.2.2 on 2023-09-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
