# Generated by Django 4.2.2 on 2023-09-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eadmin", "0002_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=32),
        ),
    ]
