# Generated by Django 4.2.2 on 2023-09-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eadmin", "0002_alter_admin_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admininfo",
            name="username",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="AdminInfo",
                to="eadmin.admin",
            ),
        ),
    ]
