# Generated by Django 4.2.2 on 2023-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eadmin", "0004_grade_section_student_subject_teacher_teacherinfo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
